### ISSUE TITLE
Does not highlight with recent vscode version

### ISSUE THREAD

**Issue by marcelcremer** [pushqrdx/vscode-inline-html#12]
Hey,

since the last update from VSCode, it seems like the highlighting is not working anymore:

![image](https://user-images.githubusercontent.com/6123724/55948122-29cdc100-5c50-11e9-9171-283490c7ba29.png)

Also it looks like the intellisense for default html tags is working:

![image](https://user-images.githubusercontent.com/6123724/55948054-01de5d80-5c50-11e9-88b0-1f0ba290dd14.png)

But Emmet is not:

![image](https://user-images.githubusercontent.com/6123724/55948077-0f93e300-5c50-11e9-8c37-77e69326ba8c.png)

(Keine Vorschläge = no results)

Best Regards
Marcel

**Comment by pushqrdx** [comment]
@marcelcremer sorry for the late reply, it's github not notifying me for some reason. So i have 1.33.1 and i just tested it out and it works as expected, can you try to disable all other extensions to see whether this is caused by so kind of collision? If still not working i would be really glad if you can provide a very bare bones test project where i can reproduce that.

**Comment by marcelcremer** [comment]
Hi @pushqrdx , 

I seem to have missed your notification. I switched to angular2-inline while it did not work and tried to reproduce the issue today - however, it's gone.

Sorry to have bothered you. If I can reproduce it somewhen later, I might reopen the ticket.

Thanks for your time, effort and the great plugin!

Cheers
Marcel
