### ISSUE TITLE
request to add a hotkey to add  /*html*/

### ISSUE THREAD

**Issue by vadimmos** [pushqrdx/vscode-inline-html#32]
It would be very convenient to add /*html*/ with some hotkey.

**Comment by pushqrdx** [comment]
@vadimmos this should be easy, i added it to todo for next update which will hopefully also fix the recent tab completion issue

**Comment by pushqrdx** [comment]
@vadimmos instead of a shortcut, i have added new `/html` and `/css` snippets so that you can just type `/h` and hit tap to expand a full inline html block, you can test it on vscode insiders using the latest build available here in the `Releases` page, i haven't published it to the store yet because i want to make sure it doesn't break anything first, if you give it a go please let me know if everything is working as expected

**Comment by vadimmos** [comment]
it's funny, that's exactly what I did so as not to write a full comment /*html*/ every time
