### ISSUE TITLE
The head of the arrow functions has an error color

### ISSUE THREAD

**Issue by laci4321** [pushqrdx/vscode-inline-html#41]
Hi! First of all: this extension is 10/10, it allows me to create dynamic HTML elements on a totally different level!

I have a little remark. The head (character: &gt) of the arrow functions inside template literal expressions has an error color.  Can you do something with it?

<img width="575" alt="image" src="https://github.com/pushqrdx/vscode-inline-html/assets/110727640/829c9d69-2406-47a8-8160-27cae41fdf47">

**Comment by pushqrdx** [comment]
@laci4321 will look into it this weekend, sorry for late reply

**Comment by pushqrdx** [comment]
@laci4321 sorry for the extremely late reply, life been a little bit busy and i didn't have enough free time to work on `inline-html`. After debugging the issue, it turns out that it's not specific to `inline-html` as the same behavior can be observed using jsx + bracket highlighting (which is a built-in vscode feature). 

Two possible solutions:
1- I'll try to report it upstream but minor annoyances like this tend to not get enough attention from the vscode team
2- Set `editor.bracketPairColorization.enabled` to `false` (which I personally do)

Anyway, again apologies for this taking so long. I'll be closing this issue.
