### ISSUE TITLE
Syntax highlighting broken is JS literal

### ISSUE THREAD

**Issue by TiLopes** [pushqrdx/vscode-inline-html#48]
With extension enabled:
![image](https://github.com/pushqrdx/vscode-inline-html/assets/106965010/265746d3-28b3-4c1f-a89d-44f04680fc6d)

Extension disabled:
![image](https://github.com/pushqrdx/vscode-inline-html/assets/106965010/82d5614b-d3e4-41de-a853-7a9e8aa01f89)

The theme used is GitHub Dark Default

**Comment by pushqrdx** [comment]
@TiLopes this is not a bug, it's because you're using `/*css*/` which expects valid CSS (so it needs a class to wrap the `background-color` property in your case)

However if you want to directly embed CSS properties use `/*style*/` which will correctly highlight your code like so:

![image](https://github.com/pushqrdx/vscode-inline-html/assets/25884937/f352c4f7-35be-4726-bf16-204e33034da5)
